name: Build and Package

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [18]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build renderer
      run: npm run build:renderer
      
    - name: Build and package for Windows
      if: matrix.os == 'windows-latest'
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false
      run: npm run build:win -- --publish never
      
    - name: Install electron-rebuild
      if: matrix.os == 'macos-latest'
      run: npm install --save-dev electron-rebuild

    - name: Rebuild sharp for Electron arm64
      if: matrix.os == 'macos-latest'
      run: npx electron-rebuild -f -w sharp --arch=arm64

    - name: Build and package for macOS arm64
      if: matrix.os == 'macos-latest'
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false
      run: npm run build:mac -- --arm64

    - name: Upload macOS arm64 artifact
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: media-converter-mac-arm64
        path: dist/*.dmg
        retention-days: 30

    - name: Rebuild sharp for Electron x64
      if: matrix.os == 'macos-latest'
      run: npx electron-rebuild -f -w sharp --arch=x64

    - name: Build and package for macOS x64
      if: matrix.os == 'macos-latest'
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false
      run: npm run build:mac -- --x64

    - name: Upload macOS x64 artifact
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: media-converter-mac-x64
        path: dist/*.dmg
        retention-days: 30

    - name: Build and package for Linux
      if: matrix.os == 'ubuntu-latest'
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false
      run: npm run build:linux -- --publish never
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: media-converter-${{ matrix.os }}
        path: dist/
        retention-days: 30 