name: Build and Package

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [arm64, x64]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install electron-rebuild
        run: npm install --save-dev electron-rebuild
      - name: Rebuild sharp for Electron
        run: npx electron-rebuild -f -w sharp --arch=${{ matrix.arch }}
      - name: Build and package for macOS
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: npm run build:mac -- --${{ matrix.arch }}
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: media-converter-mac-${{ matrix.arch }}
          path: dist/*.dmg
          retention-days: 30

  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build and package for Windows
        run: npm run build:win -- --publish never
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: media-converter-windows-latest
          path: dist/*.exe
          retention-days: 30

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build and package for Linux
        run: npm run build:linux -- --publish never
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: media-converter-ubuntu-latest
          path: dist/*.AppImage
          retention-days: 30 